<?php 
$labels = array();
$labels['settings_tab'] = 'Abwesenheitsnotiz';
$labels['settings'] = 'Abwesenheitsnotiz einrichten';
$labels['settings_status'] = 'Statusmeldungen';
$labels['dummy_message'] = 'Das Exim Vacation plugin funktioniert noch nicht.';
$labels['send_msg'] = 'Abwesenheitsnotiz aktiv';
$labels['vacation_text_field'] = 'Text der Abwesenheitsnotiz';
$labels['folder_missing'] = 'Ordner für Abwesenheitsnotiz nicht gefunden. Bitte Plugin-Konfiguration prüfen.';
$labels['folder_not_writeable'] = 'Kein Schreibrecht in Ordner für Abwesenheitsnotiz. Muss durch PHH beschreibbar sein. Bitte Ordnerrechte prüfen';
$labels['message_status_active'] = 'Aktive Abwesenheitsnotiz gefunden';
$labels['message_status_passive'] = 'Inaktive Abwesenheitsnotiz gefunden';
$labels['message_status_not_existing'] = 'Keine bestehende Abwesenheitsnotiz im Verzeichnis gefunden';
$labels['file_not_writable'] = 'Nachricht kann nicht geändert werden. Kein Schreibrecht auf Datei.';