<?php 
$labels = array();
$labels['settings_tab'] = 'Vacation message'; 
$labels['settings'] = 'Set vacation message';
$labels['settings_status'] = 'Status messages';
$labels['dummy_message'] = 'The Exim Vacation plugin isn\'t working yet.';
$labels['send_msg'] = 'Vacation message is activ';
$labels['vacation_text_field'] = 'Vacation message';
$labels['folder_missing'] = 'vacation folder doesn\'t exist. Please check your plugin configuration.';
$labels['folder_not_writeable'] = 'Cannot write to vacation folder. It has to be writeable by PHP. Please check your system configuration.';
$labels['message_status_active'] = 'Active vacation message found';
$labels['message_status_passive'] = 'Inactive vacation message found';
$labels['message_status_not_existing'] = 'Vacation folder exists, but no existing vacation message found';
$labels['file_not_writable'] = 'configuration error. No write permission for file:';